/*! Copyright (c) 2025 Aplix and/or its affiliates */(()=>{"use strict";var e={"./src/bridgeAdEventHandler.ts":
/*!*************************************!*\
  !*** ./src/bridgeAdEventHandler.ts ***!
  \*************************************/(e,t,o)=>{o.r(t),o.d(t,{BridgeAdEventHandler:()=>i});var r=o(/*! ./handlers/conversionHandler */"./src/handlers/conversionHandler.ts"),n=o(/*! ./handlers/cookieHandler */"./src/handlers/cookieHandler.ts");class i{constructor(e){this.browserInfo=e}handle(e){if(!e)return void console.warn("invalid event argument: ",e);const t=e.type,o=e.subtype,i=this.browserInfo.window,s=this.browserInfo.document;try{switch(t){case"conversion":"start"!==o&&"end"!==o||(new r.ConversionHandler).handleConversion(i,s,e);break;case"cookie":"set_id"===o&&(new n.CookieHandler).handleSetCookie(i,s),"reject"===o&&(new n.CookieHandler).handleRejectCookie(i,s);break;default:console.warn("Unknown type:",t),t||o||(e.type=null,(new r.ConversionHandler).handleConversion(i,s,e))}}catch(t){console.error("caught error at handle: ",e,t)}}}},"./src/bridgeAdEventQueueProxy.ts":
/*!****************************************!*\
  !*** ./src/bridgeAdEventQueueProxy.ts ***!
  \****************************************/(e,t,o)=>{o.r(t),o.d(t,{BridgeAdEventQueueProxy:()=>n});var r=o(/*! ./bridgeAdTagData */"./src/bridgeAdTagData.ts");class n extends Array{constructor(e){super(),this.baEventHandler=e}push(e){if(e&&"object"==typeof e){const t=e,o=new r.BridgeAdTagData(t);this.baEventHandler.handle(o)}return super.push(e)}}},"./src/bridgeAdTagData.ts":
/*!********************************!*\
  !*** ./src/bridgeAdTagData.ts ***!
  \********************************/(e,t,o)=>{o.r(t),o.d(t,{BridgeAdTagData:()=>r});class r{constructor(e){var t,o,n,i;this.type=null,this.subtype="",this.name=null,this.price=null,e instanceof r?(this.type=e.type,this.subtype=e.subtype,this.name=e.name,this.price=e.price):(this.type="type"in e&&null!==(t=e.type)&&void 0!==t?t:null,this.subtype="subtype"in e&&null!==(o=e.subtype)&&void 0!==o?o:"",this.name="name"in e&&null!==(n=e.name)&&void 0!==n?n:null,this.price="price"in e&&null!==(i=e.price)&&void 0!==i?i:null)}toObject(){return{type:this.type,subtype:this.subtype,name:this.name,price:this.price}}}},"./src/globalBrowserInformation.ts":
/*!*****************************************!*\
  !*** ./src/globalBrowserInformation.ts ***!
  \*****************************************/(e,t,o)=>{o.r(t),o.d(t,{GlobalBrowserInformation:()=>r});class r{constructor(e,t){this.window=e,this.document=t}}},"./src/handlers/conversionHandler.ts":
/*!*******************************************!*\
  !*** ./src/handlers/conversionHandler.ts ***!
  \*******************************************/(e,t,o)=>{o.r(t),o.d(t,{ConversionHandler:()=>s});var r=o(/*! ../utils/baclid */"./src/utils/baclid.ts"),n=o(/*! ../utils/cookie */"./src/utils/cookie.ts"),i=o(/*! ../utils/urlParser */"./src/utils/urlParser.ts");class s{constructor(){this.baseUrl=()=>"https://dev.meteor.bridge-ad.net/api/v1/conversions"}handleConversion(e,t,o){let r=this.getValidBaclidValueFromCookie(t);if(!r){const t=e.location;r=i.getUrlParamValue(t.href,"baclid")}if(!r)return;const n=Object.assign(Object.assign({},o.toObject()),{baclid:r}),s=JSON.stringify(n),a=this.baseUrl(),c=new Blob([s],{type:"text/plain"});navigator.sendBeacon(a,c)}getValidBaclidValueFromCookie(e){const t=n.getCookieValue(e,"bridge_ad_baclid");return r.isBaclidValid(t)?t:""}}},"./src/handlers/cookieHandler.ts":
/*!***************************************!*\
  !*** ./src/handlers/cookieHandler.ts ***!
  \***************************************/(e,t,o)=>{o.r(t),o.d(t,{CookieHandler:()=>s});var r=o(/*! ../utils/baclid */"./src/utils/baclid.ts"),n=o(/*! ../utils/cookie */"./src/utils/cookie.ts"),i=o(/*! ../utils/urlParser */"./src/utils/urlParser.ts");class s{constructor(){this.cookieRejectKey="bridge_ad_cookie_rejection",this.cookieBaclidKey="bridge_ad_baclid"}handleSetCookie(e,t){if("true"===n.getCookieValue(t,this.cookieRejectKey))return;const o=e.location;let s=i.getUrlParamValue(o.href,"baclid");if(s=r.isBaclidValid(s)?s:"",!s)return;const a=o.hostname.split(".");for(let e=0;e<a.length;e++){const o=a.slice(a.length-e-1).join(".");n.setCookie(t,this.cookieBaclidKey,s,o,30);if(n.getCookieValue(t,this.cookieBaclidKey)===s)break}}handleRejectCookie(e,t){if("true"===n.getCookieValue(t,this.cookieRejectKey))return;const o=e.location.hostname.split(".");for(let e=0;e<o.length;e++){const r=o.slice(o.length-e-1).join(".");n.setCookieWithoutExpires(t,this.cookieRejectKey,"true",r),n.deleteCookie(t,this.cookieBaclidKey,r);if("true"===n.getCookieValue(t,this.cookieRejectKey))break}}}},"./src/utils/baclid.ts":
/*!*****************************!*\
  !*** ./src/utils/baclid.ts ***!
  \*****************************/(e,t,o)=>{function r(e){return/^([^.]+\.){2}[^.]+$/.test(e)}o.r(t),o.d(t,{isBaclidValid:()=>r})},"./src/utils/cookie.ts":
/*!*****************************!*\
  !*** ./src/utils/cookie.ts ***!
  \*****************************/(e,t,o)=>{function r(e,t){var o;const r=null!==(o=e.cookie)&&void 0!==o?o:"";if(!r)return"";const n=r.split(";"),i=t+"=";for(let e of n)if(e=e.trimStart(),0===e.indexOf(i))try{return decodeURIComponent(e.substring(i.length,e.length))}catch(e){return console.warn(`getCookieValue error (name=${t}) :`,e),""}return""}function n(e,t,o,r,n){const i=encodeURIComponent(t),s=encodeURIComponent(o),a=new Date;a.setTime(a.getTime()+24*n*60*60*1e3);const c="expires="+a.toUTCString();e.cookie=`${i}=${s||""}; ${c}; domain=${r}; path=/; Secure; SameSite=Strict;`}function i(e,t,o,r){const n=encodeURIComponent(t),i=encodeURIComponent(o);e.cookie=`${n}=${i||""}; domain=${r}; path=/; Secure; SameSite=Strict;`}function s(e,t,o){const r=encodeURIComponent(t);e.cookie=`${r}=; expires=Thu, 01 Jan 1970 00:00:00 GMT; domain=${o}; path=/; Secure; SameSite=Strict;`}o.r(t),o.d(t,{deleteCookie:()=>s,getCookieValue:()=>r,setCookie:()=>n,setCookieWithoutExpires:()=>i})},"./src/utils/urlParser.ts":
/*!********************************!*\
  !*** ./src/utils/urlParser.ts ***!
  \********************************/(e,t,o)=>{function r(e,t){try{const o=new URL(e).searchParams;if(o.has(t))return o.get(t)||""}catch(e){return""}return""}o.r(t),o.d(t,{getUrlParamValue:()=>r})}},t={};function o(r){var n=t[r];if(void 0!==n)return n.exports;var i=t[r]={exports:{}};return e[r](i,i.exports,o),i.exports}o.d=(e,t)=>{for(var r in t)o.o(t,r)&&!o.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},o.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),o.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var r={};(()=>{
/*!**********************!*\
  !*** ./src/index.ts ***!
  \**********************/
o.r(r);var e=o(/*! ./bridgeAdEventHandler */"./src/bridgeAdEventHandler.ts"),t=o(/*! ./bridgeAdEventQueueProxy */"./src/bridgeAdEventQueueProxy.ts"),n=o(/*! ./bridgeAdTagData */"./src/bridgeAdTagData.ts"),i=o(/*! ./globalBrowserInformation */"./src/globalBrowserInformation.ts");const s=window,a=document;(()=>{const o=new e.BridgeAdEventHandler(new i.GlobalBrowserInformation(s,a)),r=new t.BridgeAdEventQueueProxy(o),c=s.batag_evq||[];if(c.push===Array.prototype.push)for(const e of c)try{if(e&&"object"==typeof e){const t=new n.BridgeAdTagData(e);o.handle(t)}else console.log("The argument for batag function is only one object type.",e)}catch(e){}s.batag_evq=r,s.batag=e=>{s.batag_evq.push(e)}})()})()})();
